#!/usr/bin/env python

import sys
import argparse
import re
from config import CONFIG_FOLDER, load_config, ConfigError
from msi_keyboard import MSI_Keyboard
from hidapi_wrapping import HIDLibraryError, HIDNotFoundError, HIDOpenError

VERSION = "1.0"
DEFAULT_ID = "1038:1122"

parser = argparse.ArgumentParser(description='Tool to control per-key RGB keyboard backlighting on MSI laptops. https://github.com/Askannz/msi-perkeyrgb')
parser.add_argument('-v', '--version', action='store_true', help='Prints version and exits.')
parser.add_argument('-c', '--config', action='store', metavar='FILENAME', help='Loads the configuration file with the given FILENAME. Configuration files should be put in %s. Refer to the README for syntax.' % CONFIG_FOLDER)
parser.add_argument('--id', action='store', metavar='VENDOR_ID:PRODUCT_ID', help='This argument allows you to specify the vendor/product id of your keyboard. You should not have to use this unless opening the keyboard fails with the default value. IDs are in hexadecimal format (example :  1038:1122)')

args = parser.parse_args()

if args.version:
    print("Version : %s" % VERSION)
else:
    if not args.config:
        print("Please specify a config file to load. Refer to the README for syntax.")
    else:
        if args.id:
            id_str = args.id
            if not re.fullmatch("^[0-9a-f]{4}:[0-9a-f]{4}$", id_str):
                print("Invalid syntax for vendor/product ID.")
                sys.exit(1)
        else:
            id_str = DEFAULT_ID

        try:
            colors_map = load_config(args.config)
        except ConfigError as e:
            print("Error reading config file : %s" % str(e))
        else:

            try:
                kb = MSI_Keyboard(id_str)
            except HIDLibraryError as e:
                print("Cannot open HIDAPI library : %s. Make sure you have installed libhidapi on your system, then try running \"sudo ldconfig\" to regenerate library cache." % str(e))
            except HIDNotFoundError:
                if not args.id:
                    print("No MSI keyboards with a known product/vendor IDs were found. However, if you think your keyboard should work with this program, you can try overriding the ID by adding the option \"--id VENDOR_ID:PRODUCT_ID\"")
                else:
                    print("No USB device with ID %s found." % id_str)
            except HIDOpenError:
                print("Cannot open keyboard. Possible causes :\n- You don't have permissions to open the HID device. Run this program as root, or give yourself read/write permissions to the corresponding /dev/hidraw*.\n- USB device with id %s is not a HID device." % id_str)
            else:
                kb.set_colors(colors_map)
                kb.refresh()
